# Generated by Django 3.2.9 on 2021-11-21 11:02

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='original_image',
        ),
        migrations.CreateModel(
            name='TempUrl',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('url_hash', models.CharField(max_length=32, verbose_name='Hash')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Created')),
                ('time_of_existence', models.PositiveIntegerField(help_text='Enter time of existence the link in seconds from 300 to 30000', validators=[django.core.validators.MinValueValidator(300, message='Minimum time in seconds - 300'), django.core.validators.MaxValueValidator(30000, message='Maximum time in seconds - 30000')])),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='temp_urls', to=settings.AUTH_USER_MODEL)),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='images.image')),
            ],
            options={
                'verbose_name': 'Temporary link',
                'verbose_name_plural': 'Temporary links',
                'ordering': ('-created',),
            },
        ),
    ]
